### ISSUE TITLE
v1.11 Breaks Integration with Intellisense

### ISSUE THREAD

**Issue by shubang93** [betwo/vscode-catkin-tools#17]
The plug-in was working perfect until yesterday when in VS Code decided to upgrade to the latest version. After the upgrade, it no longer loads the information for my ROS workspace correctly. The visual symptom I see is that the pop-up window on the bottom right disappears almost immediately (where as earlier it used to take some time and list packages). My current work around is to downgrade to v1.10.1. Please let me know what other information I can provide to debug this issue. 

---
Edit1: 
I am using this as part of [Remove Development Toolkit](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack). So the plug-in is installed within a Docker container.

**Comment by betwo** [comment]
Hi @shubang93, thanks for reporting this!

I have a hunch what could be the problem here: The extension now also parses which `catkin profile`s you have. Just now I found out that the file `.catkin_tools/profiles/profiles.json` is only generated if you have more than one profile available. With version `1.11.1` this is fixed for me.

It would be great if you could help me confirm or reject that. Could you please try version `1.11.1` and check if that re-enables intellisense for you?
If it does not, could you please attach log files or screenshots of the error?
[See this wiki page.](../wiki/DebuggingInstalled)

Cheers

**Comment by shubang93** [comment]
Works now! Thanks for the quick response and fix. This tool is really useful and simplifies using an IDE with ROS style workspace.
